GET localhost:8000/resolve?name=example.com&type=a&do=1

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}